### PR TITLE
Fix grading bugs

### LINKED ISSUE #121: [PE-D][Tester E] Help Button Links to AB3 UG instead of TP UG
As mentioned in the title, the help button in the GUI now links to the AB3 User Guide instead of your TP's User Guide

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: marcuslowhuiyu/ped#1

### LINKED ISSUE #163: [PE-D][Tester D] The remark does not show after remark command
After "remark 1 I love ice!!!!" The remark content just does not show in the ui. And the UG does not provide a way for user to check the remark. I notice in UG the example ui under remark did not show remark content after adding. If the app should work like this, then I think it is better clearly state some command in UG that allow user to check remark content with the remark command.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: bokun2/ped#7

### LINKED ISSUE #170: [PE-D][Tester D] Pop up window not shown after grade command
After copy the first example of grade command in UG the app just stuck and did not show the pop up window. (Test using mac)

Expected window in UG:

My command:grade MATH_CA1_100_0.5_1.0

App behavior after command:

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: bokun2/ped#8

### LINKED ISSUE #181: [PE-D][Tester A] Repeated grading is prevented
Running a grade command one after the other seems to cause any popup windows beyond the first to close. For example, grade MATH_CA1_100_0.5_1.0 after running grade ENGLISH_CA1_40_0.2_4.5 causes the window to keep closing, preventing any user input.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ConradLew/ped#17

### LINKED ISSUE #182: [PE-D][Tester C] Remarks for a student is not being displayed in the GUI
Perhaps you can consider displaying the remarks for a person, as although on adding/editing a remark using the 'remark'/'edit' commands a message is being displayed that the remark got added/edited, adding/editing remarks become a redundant feature if user cannot view the remarks after adding or editing it for a person!

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: agarwal-anjali/ped#8

### PR DESCRIPTION
**Pull request by jgyj123**
Fixes #121,
Fixes #163,
Fixes #181,
Fixes #182 
Fixes #170

### CODE REVIEW

**Review by e1010101 — APPROVED** [review]
ok

**Review by Hoodineee — APPROVED** [review]
LGTM

File: src/main/java/seedu/watson/logic/commands/GradeCommand.java [hunk 1]
```diff
@@ -26,8 +26,8 @@ public class GradeCommand extends Command {
             + "assessmentWeightage_"
             + "assessmentDifficulty\n"
             + "Example: " + COMMAND_WORD + " "
-            + "math_"
-            + "ca1_"
+            + "MATH_"
+            + "CA1_"
```
Comment (Hoodineee) [inline src/main/java/seedu/watson/logic/commands/GradeCommand.java:30]: This has been changed to be case insensitive
